### ISSUE TITLE
No SQL Layout

### ISSUE THREAD

**Issue by Visfan** [val--/keymarket_light#1]
Hey,

Your project seems very well structured and really useful, I'm just needing a .sql so my database has all the relevant tables and layout.

Could you post a .sql file to help assist me?

THANKS!!!

**Comment by val--** [comment]
Hi, this is a very simple project (structure/ files are a little messy, and french & english are often mixed :p ), but feel free to try it or contribute !

I've uploaded an .sql file : 
- table "all_games" is updated through the "script_cron.php" file. It fills the table with the latest Steam entries (last games added in their database).
- table "jeux" are the game's fields, such as price and screenshot url. This table is filled when a user adds a game in his gamelist ("scripts/ajout_jeu.php")
- table "gamelist" is the user's game list
- tale "utilisateurs" is the regular user table

**Comment by Visfan** [comment]
The SQL Layout is now working and I'm currently trying to translate a few pages from French to English :p 

I'm currently having an issue where I can't ADD any steam games to sell on my list, It just reloads the page and nothing shows up at all. I have tried inputting both a name of a game and a steam app ID.
